language: python
python:
  - "3.7.3"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
before_script:
  - pip install nltk
script:
  - pylint ./preprocessor/preprocessor.py
  - pylint ./preprocessor/preprocessor_test.py
  - pytest --cov=preprocessor