language: python
python:
  - "3.7.3"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
before_script:
  - install nltk
script:
  - pytest twitter_test.py
  - pytest --cov
  - pylint twitter.py
  - pylint twitter_test.py